[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "my-flashcard-app"
version = "0.1.0"
description = "Terminal flashcard app"
requires-python = ">=3.9"

[project.scripts]
my_flashcard_app = "flashcards.app:main"
